export { authService } from './auth'
export { dashboardService } from './dashboard'
export { usersService } from './users'
export { financeService } from './finance'
export { feeService } from './fee'
export { academicsService } from './academics'
export { accessControlService } from './access-control'
export { metadataService } from './metadata'
export { auditService } from './audit'
export { studentService } from './student'
export { parentService } from './parent'
export { inventoryService } from './inventory'
export { storage, STORAGE_KEYS } from './storage'

// Legacy services (localStorage-based, kept for modules not yet migrated)
export { tenantService } from './tenant'
export { employeeService } from './employee'
export { attendanceService } from './attendance'
export { taskService } from './task'

// Re-export key types
export type { UserListItem, ApiUserRole, CreateUserRequest, UpdateUserRequest } from './users'
export type { GlAccount, FinanceTransaction, FinanceOverview, Budget, GlAccountType, TransactionType } from './finance'
export type { FeeStructure, FeeInvoice, FeePayment, FeeReceipt, FeeDiscount, FeeComponent, FeeDashboardSummary, FeeSettings, PaymentMethod, InvoiceStatus } from './fee'
export type { AcademicClass, AcademicSection, Enrollment, EnrollmentStatus } from './academics'
export type { Student } from './student'
export type { Parent } from './parent'
export type { BootstrapResponse, DashboardSummary } from './dashboard'
export type { AuditLog } from './audit'
